rules:
- id: 1
  name: no_safety_helmet
  description: Worker without safety helmet
  template: ppe_absence
  models:
  - ppe
  params:
    person_classes:
    - person
    required_classes:
    - hardhat
    absence_classes:
    - no-hardhat
    coverage_ratio: 0.5
  severity: 3
  enabled: true
- id: 2
  name: 门口有人靠近
  description: ''
  template: zone_intrusion
  models:
  - ppe
  params:
    zones:
    - x: 0
      y: 0
      w: 0.29873417721518986
      h: 0.3457454289732771
    target_classes:
    - Person
  severity: 3
  enabled: true
- id: 13
  name: smoking_no_fire_zone
  description: Smoking detected in no-fire zone
  template: presence_near_person
  models:
  - smoking
  params:
    trigger_classes:
    - cigarette
    - smoking
    person_classes:
    - person
    overlap_margin: 0.2
    min_confidence: 0.0
  severity: 4
  enabled: true
- id: 14
  name: person_holding_cigarette
  description: Person holding/with cigarette in no-fire zone
  template: presence_near_person
  models:
  - smoking
  params:
    trigger_classes:
    - cigarette
    person_classes:
    - person
    overlap_margin: 0.1
    min_confidence: 0.0
  severity: 3
  enabled: true
